#!/bin/sh
lock() {
    #i3lock --nofork -c 000000
    i3lock --nofork -c 262626 --blur=1 --bar-indicator --bar-color=262626FF --bar-direction=0 --bar-orientation=horizontal --bar-width=10 -c 262626 --insidevercolor=FFFFFF00 --insidewrongcolor=FFFFFF00 --insidecolor=ffffff00 --ringvercolor=5F875FAA --ringwrongcolor=AF5F5FAA --ringcolor=44444400 --linecolor=44444422 --keyhlcolor=5F875FAA  --bshlcolor=AF5F5FAA
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
